import os

from yacs.config import CfgNode as CN

_C = CN()

_C.CFG_NAME = ''
_C.OUTPUT_DIR = ''
_C.LOG_DIR = ''
_C.DATA_DIR = ''
_C.GPUS = '0'
_C.WORKERS = 4
_C.PRINT_FREQ = 20
_C.AUTO_RESUME = False
_C.PIN_MEMORY = True
_C.RANK = 0
_C.VERBOSE = True
_C.DIST_BACKEND = 'nccl'
_C.DDP = True

# Cudnn related params
_C.CUDNN = CN()
_C.CUDNN.BENCHMARK = True
_C.CUDNN.DETERMINISTIC = False
_C.CUDNN.ENABLED = True

# common params for NETWORK
_C.MODEL = CN()
_C.MODEL.NAME = 'drnet'
_C.MODEL.INIT_WEIGHTS = True
_C.MODEL.PRETRAINED = ''
_C.MODEL.SYNC_BN = False
_C.MODEL.BACKBONE = CN(new_allowed=True)

_C.REFINE = CN()
_C.REFINE.USE_REFINE = False
_C.REFINE.NUM_LAYERS = 1
_C.REFINE.MAX_PROPOSAL = 120

_C.LOSS = CN()
_C.LOSS.WITH_HEATMAP_LOSS = True
_C.LOSS.HEATMAP_LOSS_FACTOR = 1.0
_C.LOSS.WITH_OFFSET_LOSS = True
_C.LOSS.OFFSET_LOSS_FACTOR = 1.0
_C.LOSS.WITH_REFINE_LOSS = False
_C.LOSS.REFINE_LOSS_FACTOR = 1.0

# DATASET related params
_C.DATASET = CN()
_C.DATASET.ROOT = 'data'
_C.DATASET.DATASET = 'ochuman'
_C.DATASET.NUM_JOINTS = 17
_C.DATASET.MAX_NUM_PEOPLE = 30
_C.DATASET.TRAIN = 'val'
_C.DATASET.TEST = 'test'
_C.DATASET.OFFSET_RADIUS = 4.0
_C.DATASET.BG_WEIGHT = 1.0

_C.DATASET.DET_TYPE = 'center'
_C.DATASET.DETKPT_NAME = ['center']
_C.DATASET.DETKPT_IDXS = [list(range(17))]

# training data augmentation
_C.DATASET.MAX_ROTATION = 30
_C.DATASET.MIN_SCALE = 0.75
_C.DATASET.MAX_SCALE = 1.25
_C.DATASET.SCALE_TYPE = 'short'
_C.DATASET.MAX_TRANSLATE = 40
_C.DATASET.INPUT_SIZE = 512
_C.DATASET.OUTPUT_SIZE = 128
_C.DATASET.FLIP = 0.5

# heatmap generator (default is OUTPUT_SIZE/64)
_C.DATASET.SIGMA = 2.0
_C.DATASET.DETKPT_SIGMA = 4.0
_C.DATASET.BASE_SIZE = 256.0
_C.DATASET.BASE_SIGMA = 2.0
_C.DATASET.MIN_SIGMA = 1

# train
_C.TRAIN = CN()
_C.TRAIN.LR_FACTOR = 0.1
_C.TRAIN.LR_STEP = [90, 120]
_C.TRAIN.LR = 0.001
_C.TRAIN.OPTIMIZER = 'adam'
_C.TRAIN.MOMENTUM = 0.9
_C.TRAIN.WD = 0.0001
_C.TRAIN.NESTEROV = False
_C.TRAIN.GAMMA1 = 0.99
_C.TRAIN.GAMMA2 = 0.0
_C.TRAIN.BEGIN_EPOCH = 0
_C.TRAIN.END_EPOCH = 140
_C.TRAIN.RESUME = False
_C.TRAIN.CHECKPOINT = ''
_C.TRAIN.IMAGES_PER_GPU = 10
_C.TRAIN.SHUFFLE = True

# testing
_C.TEST = CN()
_C.TEST.IMAGES_PER_GPU = 1
_C.TEST.FLIP_TEST = True
_C.TEST.SCALE_FACTOR = [1]
_C.TEST.MODEL_FILE = ''
_C.TEST.OKS_SCORE = 0.7
_C.TEST.OKS_SIGMAS = []
_C.TEST.KEYPOINT_THRESHOLD = 0.01
_C.TEST.POOL_THRESHOLD1 = 300
_C.TEST.POOL_THRESHOLD2 = 200

_C.TEST.LOG_PROGRESS = True

if __name__ == '__main__':
    import sys

    with open(sys.argv[1], 'w') as f:
        print(_C, file=f)
